"""add durable provider call leases

Revision ID: 132931969d6b
Revises: 369e6194e3cb
Create Date: 2026-08-09 03:43:43.359067
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "132931969d6b"
down_revision: str | None = "369e6194e3cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_call_leases",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("call_key", sa.String(length=240), nullable=False),
        sa.Column("lease_owner", sa.String(length=160), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.id"],
            name=op.f("fk_provider_call_leases_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_call_leases")),
        sa.UniqueConstraint("run_id", "call_key", name=op.f("uq_provider_call_leases_run_id")),
    )
    op.create_index(
        "ix_provider_call_leases_run_expiry",
        "provider_call_leases",
        ["run_id", "lease_expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_provider_call_leases_run_expiry", table_name="provider_call_leases")
    op.drop_table("provider_call_leases")
    # ### end Alembic commands ###
