"""create v0.1 persistence schema

Revision ID: 369e6194e3cb
Revises:
Create Date: 2026-08-09 03:37:40.404292
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "369e6194e3cb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

APPEND_ONLY_TABLES = (
    "mission_revisions",
    "raw_signal_revisions",
    "atomic_claims",
    "opportunity_score_snapshots",
    "critic_results",
    "product_hypotheses",
    "lifecycle_events",
    "agent_calls",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "atomic_claims",
        sa.Column("subject_type", sa.String(length=64), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("claim_type", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("evidence_ids", sa.ARRAY(sa.UUID()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'SUPPORTED' OR cardinality(evidence_ids) > 0",
            name=op.f("ck_atomic_claims_supported_has_evidence"),
        ),
        sa.CheckConstraint(
            "status IN ('SUPPORTED', 'HYPOTHESIS', 'UNKNOWN', "
            "'INSUFFICIENT_EVIDENCE', 'RESEARCH_UNAVAILABLE')",
            name=op.f("ck_atomic_claims_valid_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_atomic_claims")),
    )
    op.create_index(
        "ix_atomic_claims_subject",
        "atomic_claims",
        ["subject_type", "subject_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "canonical_problems",
        sa.Column("canonical_key", sa.String(length=240), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canonical_problems")),
        sa.UniqueConstraint("canonical_key", name=op.f("uq_canonical_problems_canonical_key")),
    )
    op.create_index("ix_canonical_problems_status", "canonical_problems", ["status"], unique=False)
    op.create_table(
        "competitors",
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("normalized_name", sa.String(length=240), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("alternative_type", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competitors")),
        sa.UniqueConstraint(
            "normalized_name", "canonical_url", name=op.f("uq_competitors_normalized_name")
        ),
    )
    op.create_table(
        "raw_signals",
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=512), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("parent_external_id", sa.String(length=512), nullable=True),
        sa.Column("author_pseudonym", sa.String(length=128), nullable=True),
        sa.Column("author_kind", sa.String(length=24), nullable=False),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_tombstone", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_signals")),
        sa.UniqueConstraint("source", "external_id", name=op.f("uq_raw_signals_source")),
    )
    op.create_index(
        "ix_raw_signals_author_pseudonym", "raw_signals", ["author_pseudonym"], unique=False
    )
    op.create_index("ix_raw_signals_canonical_url", "raw_signals", ["canonical_url"], unique=False)
    op.create_index(
        "ix_raw_signals_source_collected", "raw_signals", ["source", "collected_at"], unique=False
    )
    op.create_table(
        "research_missions",
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'ACTIVE', 'PAUSED', 'ARCHIVED')",
            name=op.f("ck_research_missions_valid_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_missions")),
    )
    op.create_index(
        "ix_research_missions_status_created",
        "research_missions",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "competitor_evidence",
        sa.Column("competitor_id", sa.UUID(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("captured_excerpt", sa.Text(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("evidence_kind", sa.String(length=64), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competitor_id"],
            ["competitors.id"],
            name=op.f("fk_competitor_evidence_competitor_id_competitors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competitor_evidence")),
        sa.UniqueConstraint(
            "competitor_id",
            "source_url",
            "content_hash",
            name=op.f("uq_competitor_evidence_competitor_id"),
        ),
    )
    op.create_index(
        "ix_competitor_evidence_observed",
        "competitor_evidence",
        ["competitor_id", "observed_at"],
        unique=False,
    )
    op.create_table(
        "gap_hypotheses",
        sa.Column("canonical_problem_id", sa.UUID(), nullable=False),
        sa.Column("gap_type", sa.String(length=64), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("user_evidence_ids", sa.ARRAY(sa.UUID()), nullable=False),
        sa.Column("competitor_evidence_ids", sa.ARRAY(sa.UUID()), nullable=False),
        sa.Column("contradicting_claim_ids", sa.ARRAY(sa.UUID()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cardinality(competitor_evidence_ids) > 0",
            name=op.f("ck_gap_hypotheses_has_competitor_evidence"),
        ),
        sa.CheckConstraint(
            "cardinality(user_evidence_ids) > 0", name=op.f("ck_gap_hypotheses_has_user_evidence")
        ),
        sa.ForeignKeyConstraint(
            ["canonical_problem_id"],
            ["canonical_problems.id"],
            name=op.f("fk_gap_hypotheses_canonical_problem_id_canonical_problems"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gap_hypotheses")),
    )
    op.create_index(
        "ix_gap_hypotheses_problem_created",
        "gap_hypotheses",
        ["canonical_problem_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "mission_revisions",
        sa.Column("mission_id", sa.UUID(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("parent_revision_id", sa.UUID(), nullable=True),
        sa.Column("change_reason", sa.Text(), nullable=False),
        sa.Column("mission_text", sa.Text(), nullable=False),
        sa.Column("original_language", sa.String(length=32), nullable=False),
        sa.Column("output_locale", sa.String(length=32), nullable=False),
        sa.Column("interpretation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "revision_number >= 1", name=op.f("ck_mission_revisions_positive_revision_number")
        ),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["research_missions.id"],
            name=op.f("fk_mission_revisions_mission_id_research_missions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_revision_id"],
            ["mission_revisions.id"],
            name=op.f("fk_mission_revisions_parent_revision_id_mission_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mission_revisions")),
        sa.UniqueConstraint(
            "mission_id", "revision_number", name=op.f("uq_mission_revisions_mission_id")
        ),
    )
    op.create_index(
        "ix_mission_revisions_mission_created",
        "mission_revisions",
        ["mission_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "problem_clusters",
        sa.Column("canonical_problem_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("last_growth_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["canonical_problem_id"],
            ["canonical_problems.id"],
            name=op.f("fk_problem_clusters_canonical_problem_id_canonical_problems"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_problem_clusters")),
    )
    op.create_index(
        "ix_problem_clusters_problem_status",
        "problem_clusters",
        ["canonical_problem_id", "status"],
        unique=False,
    )
    op.create_table(
        "raw_signal_revisions",
        sa.Column("raw_signal_id", sa.UUID(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("original_language", sa.String(length=32), nullable=False),
        sa.Column("engagement", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("normalization_version", sa.String(length=32), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_tombstone", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "revision_number >= 1", name=op.f("ck_raw_signal_revisions_positive_revision_number")
        ),
        sa.ForeignKeyConstraint(
            ["raw_signal_id"],
            ["raw_signals.id"],
            name=op.f("fk_raw_signal_revisions_raw_signal_id_raw_signals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_signal_revisions")),
        sa.UniqueConstraint(
            "raw_signal_id", "content_hash", name="uq_raw_signal_revisions_content"
        ),
        sa.UniqueConstraint(
            "raw_signal_id", "revision_number", name="uq_raw_signal_revisions_version"
        ),
    )
    op.create_index(
        "ix_raw_signal_revisions_hash", "raw_signal_revisions", ["content_hash"], unique=False
    )
    op.create_table(
        "opportunities",
        sa.Column("canonical_problem_id", sa.UUID(), nullable=False),
        sa.Column("gap_hypothesis_id", sa.UUID(), nullable=False),
        sa.Column("canonical_key", sa.String(length=240), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["canonical_problem_id"],
            ["canonical_problems.id"],
            name=op.f("fk_opportunities_canonical_problem_id_canonical_problems"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["gap_hypothesis_id"],
            ["gap_hypotheses.id"],
            name=op.f("fk_opportunities_gap_hypothesis_id_gap_hypotheses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunities")),
        sa.UniqueConstraint("canonical_key", name=op.f("uq_opportunities_canonical_key")),
    )
    op.create_index(
        "ix_opportunities_problem", "opportunities", ["canonical_problem_id"], unique=False
    )
    op.create_table(
        "pain_signals",
        sa.Column("raw_signal_revision_id", sa.UUID(), nullable=False),
        sa.Column("extraction_version", sa.String(length=32), nullable=False),
        sa.Column("cluster_status", sa.String(length=24), nullable=False),
        sa.Column("pain", sa.Text(), nullable=False),
        sa.Column("user_context", sa.Text(), nullable=True),
        sa.Column("jtbd", sa.Text(), nullable=True),
        sa.Column("severity", sa.Float(), nullable=True),
        sa.Column("frequency", sa.String(length=64), nullable=True),
        sa.Column("workaround", sa.Text(), nullable=True),
        sa.Column("existing_solution", sa.Text(), nullable=True),
        sa.Column("signals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_pain_signals_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["raw_signal_revision_id"],
            ["raw_signal_revisions.id"],
            name=op.f("fk_pain_signals_raw_signal_revision_id_raw_signal_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pain_signals")),
        sa.UniqueConstraint(
            "raw_signal_revision_id",
            "extraction_version",
            name=op.f("uq_pain_signals_raw_signal_revision_id"),
        ),
    )
    op.create_index(
        "ix_pain_signals_status_created",
        "pain_signals",
        ["cluster_status", "created_at"],
        unique=False,
    )
    op.create_table(
        "research_runs",
        sa.Column("mission_revision_id", sa.UUID(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("budget_limits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("budget_used", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_checkpoint", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("mode IN ('HUNT', 'MONITOR')", name=op.f("ck_research_runs_valid_mode")),
        sa.CheckConstraint(
            "status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', "
            "'BUDGET_EXHAUSTED', 'AUTH_REQUIRED', 'FAILED', 'CANCELLED')",
            name=op.f("ck_research_runs_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["mission_revision_id"],
            ["mission_revisions.id"],
            name=op.f("fk_research_runs_mission_revision_id_mission_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_runs")),
    )
    op.create_index(
        "ix_research_runs_status_priority",
        "research_runs",
        ["status", "priority", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_research_runs_one_global_active",
        "research_runs",
        [sa.literal_column("((1))")],
        unique=True,
        postgresql_where=sa.text("status = 'RUNNING'"),
    )
    op.create_index(
        "uq_research_runs_revision_active",
        "research_runs",
        ["mission_revision_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING')"),
    )
    op.create_table(
        "evidence_cards",
        sa.Column("canonical_problem_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=32), nullable=False),
        sa.Column("independent_authors", sa.Integer(), nullable=False),
        sa.Column("independent_threads", sa.Integer(), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("supporting_claim_ids", sa.ARRAY(sa.UUID()), nullable=False),
        sa.Column("contradicting_claim_ids", sa.ARRAY(sa.UUID()), nullable=False),
        sa.Column("representative_signal_ids", sa.ARRAY(sa.UUID()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("missing_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_evidence_cards_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["canonical_problem_id"],
            ["canonical_problems.id"],
            name=op.f("fk_evidence_cards_canonical_problem_id_canonical_problems"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.id"],
            name=op.f("fk_evidence_cards_run_id_research_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_cards")),
    )
    op.create_index(
        "ix_evidence_cards_problem_created",
        "evidence_cards",
        ["canonical_problem_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "mission_opportunity_assessments",
        sa.Column("mission_revision_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=24), nullable=False),
        sa.Column("relevance", sa.Float(), nullable=False),
        sa.Column("verdict", sa.String(length=24), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lifecycle_status IN ('DISCOVERED', 'RESEARCHING', 'RESEARCH_MORE', "
            "'VALIDATE', 'REJECTED')",
            name=op.f("ck_mission_opportunity_assessments_valid_lifecycle_status"),
        ),
        sa.ForeignKeyConstraint(
            ["mission_revision_id"],
            ["mission_revisions.id"],
            name=op.f("fk_mission_opportunity_assessments_mission_revision_id_mission_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_mission_opportunity_assessments_opportunity_id_opportunities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mission_opportunity_assessments")),
        sa.UniqueConstraint(
            "mission_revision_id",
            "opportunity_id",
            name=op.f("uq_mission_opportunity_assessments_mission_revision_id"),
        ),
    )
    op.create_index(
        "ix_assessments_revision_status",
        "mission_opportunity_assessments",
        ["mission_revision_id", "lifecycle_status", "updated_at"],
        unique=False,
    )
    op.create_table(
        "problem_cluster_memberships",
        sa.Column("problem_cluster_id", sa.UUID(), nullable=False),
        sa.Column("pain_signal_id", sa.UUID(), nullable=False),
        sa.Column("similarity", sa.Float(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("removed_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "similarity >= 0 AND similarity <= 1",
            name=op.f("ck_problem_cluster_memberships_similarity_range"),
        ),
        sa.ForeignKeyConstraint(
            ["pain_signal_id"],
            ["pain_signals.id"],
            name=op.f("fk_problem_cluster_memberships_pain_signal_id_pain_signals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["problem_cluster_id"],
            ["problem_clusters.id"],
            name=op.f("fk_problem_cluster_memberships_problem_cluster_id_problem_clusters"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_problem_cluster_memberships")),
        sa.UniqueConstraint(
            "problem_cluster_id",
            "pain_signal_id",
            name=op.f("uq_problem_cluster_memberships_problem_cluster_id"),
        ),
    )
    op.create_index(
        "ix_cluster_memberships_pain",
        "problem_cluster_memberships",
        ["pain_signal_id"],
        unique=False,
    )
    op.create_table(
        "research_tasks",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("task_type", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=240), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checkpoint", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("retry_class", sa.String(length=80), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_owner", sa.String(length=160), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'LEASED', 'SUCCEEDED', 'FAILED', 'CANCELLED')",
            name=op.f("ck_research_tasks_valid_status"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_research_tasks_nonnegative_attempt_count")
        ),
        sa.CheckConstraint(
            "max_attempts >= 1", name=op.f("ck_research_tasks_positive_max_attempts")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.id"],
            name=op.f("fk_research_tasks_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_tasks")),
        sa.UniqueConstraint("run_id", "idempotency_key", name=op.f("uq_research_tasks_run_id")),
    )
    op.create_index(
        "ix_research_tasks_claim",
        "research_tasks",
        ["status", "available_at", "priority", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_research_tasks_lease_expiry", "research_tasks", ["lease_expires_at"], unique=False
    )
    op.create_table(
        "source_checkpoints",
        sa.Column("mission_revision_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("cursor", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("watermark_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_successful_run_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["last_successful_run_id"],
            ["research_runs.id"],
            name=op.f("fk_source_checkpoints_last_successful_run_id_research_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["mission_revision_id"],
            ["mission_revisions.id"],
            name=op.f("fk_source_checkpoints_mission_revision_id_mission_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_checkpoints")),
        sa.UniqueConstraint(
            "mission_revision_id", "source", name=op.f("uq_source_checkpoints_mission_revision_id")
        ),
    )
    op.create_index(
        "ix_source_checkpoints_source_watermark",
        "source_checkpoints",
        ["source", "watermark_at"],
        unique=False,
    )
    op.create_table(
        "agent_calls",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("requested_model", sa.String(length=160), nullable=False),
        sa.Column("resolved_model", sa.String(length=160), nullable=True),
        sa.Column("effort", sa.String(length=16), nullable=False),
        sa.Column("cli_version", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("duration_ms", sa.BigInteger(), nullable=False),
        sa.Column("repair_attempts", sa.Integer(), nullable=False),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_class", sa.String(length=80), nullable=True),
        sa.Column("output_sha256", sa.LargeBinary(length=32), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("duration_ms >= 0", name=op.f("ck_agent_calls_nonnegative_duration")),
        sa.CheckConstraint(
            "repair_attempts >= 0 AND repair_attempts <= 1",
            name=op.f("ck_agent_calls_repair_attempt_range"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.id"],
            name=op.f("fk_agent_calls_run_id_research_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["research_tasks.id"],
            name=op.f("fk_agent_calls_task_id_research_tasks"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_calls")),
    )
    op.create_index(
        "ix_agent_calls_run_created", "agent_calls", ["run_id", "created_at"], unique=False
    )
    op.create_table(
        "lifecycle_events",
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("from_status", sa.String(length=24), nullable=True),
        sa.Column("to_status", sa.String(length=24), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["mission_opportunity_assessments.id"],
            name=op.f("fk_lifecycle_events_assessment_id_mission_opportunity_assessments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.id"],
            name=op.f("fk_lifecycle_events_run_id_research_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lifecycle_events")),
    )
    op.create_index(
        "ix_lifecycle_events_assessment_created",
        "lifecycle_events",
        ["assessment_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "opportunity_score_snapshots",
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=32), nullable=False),
        sa.Column("raw_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_strength", sa.Float(), nullable=False),
        sa.Column("opportunity_fit", sa.Float(), nullable=False),
        sa.Column("weights", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("penalties", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("final_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_opportunity_score_snapshots_confidence_range"),
        ),
        sa.CheckConstraint(
            "final_score >= 0 AND final_score <= 100",
            name=op.f("ck_opportunity_score_snapshots_final_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["mission_opportunity_assessments.id"],
            name=op.f(
                "fk_opportunity_score_snapshots_assessment_id_mission_opportunity_assessments"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.id"],
            name=op.f("fk_opportunity_score_snapshots_run_id_research_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_score_snapshots")),
    )
    op.create_index(
        "ix_score_snapshots_assessment_created",
        "opportunity_score_snapshots",
        ["assessment_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "problem_hypotheses",
        sa.Column("canonical_problem_id", sa.UUID(), nullable=False),
        sa.Column("evidence_card_id", sa.UUID(), nullable=False),
        sa.Column("icp", sa.Text(), nullable=False),
        sa.Column("jtbd", sa.Text(), nullable=False),
        sa.Column("trigger", sa.Text(), nullable=False),
        sa.Column("current_behavior", sa.Text(), nullable=False),
        sa.Column("pain", sa.Text(), nullable=False),
        sa.Column("workflow_failure", sa.Text(), nullable=False),
        sa.Column("falsifier", sa.Text(), nullable=False),
        sa.Column("supporting_claim_ids", sa.ARRAY(sa.UUID()), nullable=False),
        sa.Column("contradicting_claim_ids", sa.ARRAY(sa.UUID()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["canonical_problem_id"],
            ["canonical_problems.id"],
            name=op.f("fk_problem_hypotheses_canonical_problem_id_canonical_problems"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_card_id"],
            ["evidence_cards.id"],
            name=op.f("fk_problem_hypotheses_evidence_card_id_evidence_cards"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_problem_hypotheses")),
    )
    op.create_index(
        "ix_problem_hypotheses_problem",
        "problem_hypotheses",
        ["canonical_problem_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "product_hypotheses",
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("requested_by", sa.String(length=160), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_card_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["mission_opportunity_assessments.id"],
            name=op.f("fk_product_hypotheses_assessment_id_mission_opportunity_assessments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_card_id"],
            ["evidence_cards.id"],
            name=op.f("fk_product_hypotheses_evidence_card_id_evidence_cards"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_hypotheses")),
    )
    op.create_index(
        "ix_product_hypotheses_assessment",
        "product_hypotheses",
        ["assessment_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "critic_results",
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("agent_call_id", sa.UUID(), nullable=False),
        sa.Column("verdict", sa.String(length=24), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("fatal_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("weak_assumptions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("contradictions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("missing_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recommended_intents", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "verdict IN ('REJECT', 'RESEARCH_MORE', 'VALIDATE')",
            name=op.f("ck_critic_results_valid_verdict"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_critic_results_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["agent_call_id"],
            ["agent_calls.id"],
            name=op.f("fk_critic_results_agent_call_id_agent_calls"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["mission_opportunity_assessments.id"],
            name=op.f("fk_critic_results_assessment_id_mission_opportunity_assessments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.id"],
            name=op.f("fk_critic_results_run_id_research_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_critic_results")),
    )
    op.create_index(
        "ix_critic_results_assessment_created",
        "critic_results",
        ["assessment_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "merge_candidates",
        sa.Column("left_problem_id", sa.UUID(), nullable=False),
        sa.Column("right_problem_id", sa.UUID(), nullable=False),
        sa.Column("similarity", sa.Float(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("lifecycle_event_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "left_problem_id <> right_problem_id",
            name=op.f("ck_merge_candidates_different_problems"),
        ),
        sa.CheckConstraint(
            "similarity >= 0 AND similarity <= 1", name=op.f("ck_merge_candidates_similarity_range")
        ),
        sa.ForeignKeyConstraint(
            ["left_problem_id"],
            ["canonical_problems.id"],
            name=op.f("fk_merge_candidates_left_problem_id_canonical_problems"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lifecycle_event_id"],
            ["lifecycle_events.id"],
            name=op.f("fk_merge_candidates_lifecycle_event_id_lifecycle_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["right_problem_id"],
            ["canonical_problems.id"],
            name=op.f("fk_merge_candidates_right_problem_id_canonical_problems"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merge_candidates")),
        sa.UniqueConstraint(
            "left_problem_id", "right_problem_id", name=op.f("uq_merge_candidates_left_problem_id")
        ),
    )
    op.create_index(
        "ix_merge_candidates_status_created",
        "merge_candidates",
        ["status", "created_at"],
        unique=False,
    )
    op.execute(
        """
        CREATE FUNCTION gapforge_reject_append_only_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'table % is append-only', TG_TABLE_NAME;
        END;
        $$
        """
    )
    for table_name in APPEND_ONLY_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table_name}_append_only "
            f"BEFORE UPDATE OR DELETE ON {table_name} "
            "FOR EACH ROW EXECUTE FUNCTION gapforge_reject_append_only_mutation()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_merge_candidates_status_created", table_name="merge_candidates")
    op.drop_table("merge_candidates")
    op.drop_index("ix_critic_results_assessment_created", table_name="critic_results")
    op.drop_table("critic_results")
    op.drop_index("ix_product_hypotheses_assessment", table_name="product_hypotheses")
    op.drop_table("product_hypotheses")
    op.drop_index("ix_problem_hypotheses_problem", table_name="problem_hypotheses")
    op.drop_table("problem_hypotheses")
    op.drop_index("ix_score_snapshots_assessment_created", table_name="opportunity_score_snapshots")
    op.drop_table("opportunity_score_snapshots")
    op.drop_index("ix_lifecycle_events_assessment_created", table_name="lifecycle_events")
    op.drop_table("lifecycle_events")
    op.drop_index("ix_agent_calls_run_created", table_name="agent_calls")
    op.drop_table("agent_calls")
    op.drop_index("ix_source_checkpoints_source_watermark", table_name="source_checkpoints")
    op.drop_table("source_checkpoints")
    op.drop_index("ix_research_tasks_lease_expiry", table_name="research_tasks")
    op.drop_index("ix_research_tasks_claim", table_name="research_tasks")
    op.drop_table("research_tasks")
    op.drop_index("ix_cluster_memberships_pain", table_name="problem_cluster_memberships")
    op.drop_table("problem_cluster_memberships")
    op.drop_index("ix_assessments_revision_status", table_name="mission_opportunity_assessments")
    op.drop_table("mission_opportunity_assessments")
    op.drop_index("ix_evidence_cards_problem_created", table_name="evidence_cards")
    op.drop_table("evidence_cards")
    op.drop_index(
        "uq_research_runs_revision_active",
        table_name="research_runs",
        postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING')"),
    )
    op.drop_index(
        "uq_research_runs_one_global_active",
        table_name="research_runs",
        postgresql_where=sa.text("status = 'RUNNING'"),
    )
    op.drop_index("ix_research_runs_status_priority", table_name="research_runs")
    op.drop_table("research_runs")
    op.drop_index("ix_pain_signals_status_created", table_name="pain_signals")
    op.drop_table("pain_signals")
    op.drop_index("ix_opportunities_problem", table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_index("ix_raw_signal_revisions_hash", table_name="raw_signal_revisions")
    op.drop_table("raw_signal_revisions")
    op.drop_index("ix_problem_clusters_problem_status", table_name="problem_clusters")
    op.drop_table("problem_clusters")
    op.drop_index("ix_mission_revisions_mission_created", table_name="mission_revisions")
    op.drop_table("mission_revisions")
    op.drop_index("ix_gap_hypotheses_problem_created", table_name="gap_hypotheses")
    op.drop_table("gap_hypotheses")
    op.drop_index("ix_competitor_evidence_observed", table_name="competitor_evidence")
    op.drop_table("competitor_evidence")
    op.drop_index("ix_research_missions_status_created", table_name="research_missions")
    op.drop_table("research_missions")
    op.drop_index("ix_raw_signals_source_collected", table_name="raw_signals")
    op.drop_index("ix_raw_signals_canonical_url", table_name="raw_signals")
    op.drop_index("ix_raw_signals_author_pseudonym", table_name="raw_signals")
    op.drop_table("raw_signals")
    op.drop_table("competitors")
    op.drop_index("ix_canonical_problems_status", table_name="canonical_problems")
    op.drop_table("canonical_problems")
    op.drop_index("ix_atomic_claims_subject", table_name="atomic_claims")
    op.drop_table("atomic_claims")
    op.execute("DROP FUNCTION IF EXISTS gapforge_reject_append_only_mutation()")
    # ### end Alembic commands ###
