#!/bin/sh
set -eu

interval=${BACKUP_INTERVAL_SECONDS:-86400}
case "$interval" in
    *[!0-9]*|'')
        echo "BACKUP_INTERVAL_SECONDS must be an integer" >&2
        exit 2
        ;;
esac
if [ "$interval" -lt 3600 ]; then
    echo "BACKUP_INTERVAL_SECONDS must be at least 3600" >&2
    exit 2
fi

while true; do
    if gap backup create --json; then
        sleep "$interval"
    else
        sleep 300
    fi
done
